name: pocketvec_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - openbabel
  - rdkit
  - matplotlib
  - jupyterlab
  - ipykernel
  - tqdm
  - seaborn
  - scikit-learn
  - biopython
  - pip
  - pip:
      - biobb-structure-checking
